In [83]:
import pandas as pd
import numpy as np
df=pd.read_csv("vgsales.csv")

In [84]:
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [85]:
df.shape

(16598, 11)

In [86]:
df.describe()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16327.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,2006.406443,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.853933,5.828981,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

In [87]:
from sklearn.preprocessing import LabelEncoder

In [88]:
le=LabelEncoder()

In [89]:
df['Platform']=le.fit_transform(df['Platform'])
df['Platform']

0        26
1        11
2        26
3        26
4         5
         ..
16593     6
16594     7
16595    16
16596     4
16597     6
Name: Platform, Length: 16598, dtype: int64

In [90]:
df['Genre']=le.fit_transform(df['Genre'])
df['Genre']

0        10
1         4
2         6
3        10
4         7
         ..
16593     4
16594     8
16595     6
16596     5
16597     4
Name: Genre, Length: 16598, dtype: int64

In [91]:
df['Publisher']=le.fit_transform(df['Publisher'])
df['Publisher']

0        359
1        359
2        359
3        359
4        359
        ...
16593    269
16594    241
16595     21
16596      8
16597    546
Name: Publisher, Length: 16598, dtype: int64

In [92]:
df.fillna(0000,inplace=True)

In [93]:
df.describe()

,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,15.797988,1973.647307,4.928124,294.602542,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.853933,8.392298,254.346809,3.762015,178.087732,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,7.000000,2003.000000,1.000000,137.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,16.000000,2007.000000,5.000000,323.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,21.000000,2010.000000,8.000000,461.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,30.000000,2020.000000,11.000000,578.000000,41.490000,29.020000,10.220000,10.570000,82.740000

In [94]:
x=df.drop(columns=['Name'])
x

,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,26,2006.0,10,359,41.49,29.02,3.77,8.46,82.74
1,2,11,1985.0,4,359,29.08,3.58,6.81,0.77,40.24
2,3,26,2008.0,6,359,15.85,12.88,3.79,3.31,35.82
3,4,26,2009.0,10,359,15.75,11.01,3.28,2.96,33.00
4,5,5,1996.0,7,359,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...
16593,16596,6,2002.0,4,269,0.01,0.00,0.00,0.00,0.01
16594,16597,7,2003.0,8,241,0.01,0.00,0.00,0.00,0.01
16595,16598,16,2008.0,6,21,0.00,0.00,0.00,0.00,0.01
16596,16599,4,2010.0,5,8,0.00,0.01,0.00,0.00,0.01
16597,16600,6,2003.0,4,546,0.01,0.00,0.00,0.00,0.01

In [95]:
y=df['Name']
y

0                                              Wii Sports
1                                       Super Mario Bros.
2                                          Mario Kart Wii
3                                       Wii Sports Resort
4                                Pokemon Red/Pokemon Blue
                               ...
16593                  Woody Woodpecker in Crazy Castle 5
16594                       Men in Black II: Alien Escape
16595    SCORE International Baja 1000: The Official Game
16596                                          Know How 2
16597                                    Spirits & Spells
Name: Name, Length: 16598, dtype: object

In [96]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [97]:
x_train

,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
14303,14306,19,2006.0,3,340,0.03,0.00,0.00,0.00,0.03
13455,13457,4,2008.0,9,525,0.04,0.00,0.00,0.00,0.04
6724,6726,17,2015.0,0,446,0.00,0.00,0.25,0.00,0.25
898,900,13,2003.0,9,138,1.03,0.80,0.00,0.09,1.92
8484,8486,4,2010.0,7,465,0.12,0.00,0.03,0.01,0.16
...,...,...,...,...,...,...,...,...,...,...
11284,11286,19,2009.0,10,462,0.08,0.00,0.00,0.01,0.08
11964,11966,16,2008.0,0,275,0.03,0.03,0.00,0.01,0.07
5390,5392,26,2011.0,0,525,0.13,0.17,0.00,0.04,0.34
860,862,16,2002.0,4,529,0.74,0.95,0.00,0.28,1.97
15795,15798,13,2006.0,9,525,0.00,0.01,0.00,0.00,0.02

In [98]:
x_test

,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
8928,8930,13,2012.0,6,91,0.01,0.11,0.00,0.03,0.15
4789,4791,17,2007.0,0,21,0.32,0.04,0.01,0.04,0.40
15492,15495,13,2003.0,11,137,0.00,0.02,0.00,0.00,0.02
14767,14770,13,2007.0,9,138,0.01,0.01,0.00,0.00,0.03
5211,5213,17,2009.0,3,21,0.20,0.11,0.00,0.05,0.36
...,...,...,...,...,...,...,...,...,...,...
4100,4102,28,2010.0,8,21,0.20,0.24,0.00,0.05,0.48
833,835,16,2005.0,0,525,0.71,1.02,0.00,0.31,2.04
15702,15705,19,2009.0,1,412,0.00,0.00,0.02,0.00,0.02
10279,10281,16,2003.0,11,500,0.05,0.04,0.00,0.01,0.11
10854,10856,4,2008.0,10,138,0.07,0.02,0.00,0.01,0.09

In [99]:
y_train

14303            Stacked with Daniel Negreanu
13455    National Geographic Panda (US sales)
6724           Yakuza Zero: The Place of Oath
898                    The Sims: Makin' Magic
8484           Lufia: Curse of the Sinistrals
                         ...
11284               Major League Baseball 2K9
11964                    Silent Hill: Origins
5390       The Adventures of Tintin: The Game
860                Spyro: Enter the Dragonfly
15795                       Star Trek: Legacy
Name: Name, Length: 13278, dtype: object

In [100]:
y_test

8928                                               F1 2012
4789     Transformers: The Game (XBox 360, PS2, PS3, Wi...
15492                      Commandos 3: Destination Berlin
14767                               The Sims 2: Bon Voyage
5211                               Guitar Hero: Smash Hits
                               ...
4100                           James Bond 007: Blood Stone
833      Peter Jackson's King Kong: The Official Game o...
15702                  Planetarian: Chiisana Hoshi no Yume
10279                                    Dynasty Tactics 2
10854                                        FIFA Street 3
Name: Name, Length: 3320, dtype: object

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [101]:
from sklearn.tree import DecisionTreeClassifier

In [102]:
model=DecisionTreeClassifier()

In [103]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [104]:
from sklearn.metrics import accuracy_score

In [105]:
score=accuracy_score(y_test,predictions)
score

0.11566265060240964

In [107]:
rank=int(input("enter the rank:"))
platform=int(input("enter the platform:"))
year=int(input("enter the year:"))
genre=int(input("enter the genre:"))
publisher=int(input("enter the publisher:"))
na_sales=int(input("enter na sales:"))
eu_sales=int(input("enter eu sales:"))
jp_sales=int(input("enter jp sales:"))
other_sales=int(input("enter other sales:"))
global_sales=int(input("enter global sales:"))

abc=[rank,platform,year,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales]
input1=abc

input1_as_numpy_array=np.asarray(input1)
input1_reshaped=input1_as_numpy_array.reshape(1,-1)
prediction=model.predict(input1_reshaped)
Name=prediction
print("prediction:",prediction)
print("name of the game:",Name)

enter the rank: 56
enter the platform: 17
enter the year: 2007
enter the genre: 10
enter the publisher: 21
enter na sales: 32
enter eu sales: 24
enter jp sales: 2
enter other sales: 5
enter global sales: 48

prediction: ["Tony Hawk's Proving Ground"]
name of the game: ["Tony Hawk's Proving Ground"]

C:\Users\aiswa\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(